### ISSUE TITLE
hi,哥们，还在开发吗？打算持续迭代吗？

### ISSUE THREAD

**Issue by hhhaiai** [Richard-Tang/AndroidKiller4J#2]
hi,哥们，还在开发吗？打算持续迭代吗？

**Comment by zhaohaoran123** [comment]
hi,哥们，还在开发吗？打算持续迭代吗？或者有更好的替代工具么

**Comment by Richard-Tang** [comment]
> hi,哥们，还在开发吗？打算持续迭代吗？

😅 鸽太久了，最近会进行更新迭代。

**Comment by hhhaiai** [comment]
如果开始开发，可以拉一个，PR还是可以的 @Richard-Tang

**Comment by Richard-Tang** [comment]
> hhhaiai

hey 老哥方便加个vx吗？

**Comment by hhhaiai** [comment]
> 
给你个邮箱吧：sdk10001@analysys.com.cn  邮箱联系
